### PR TITLE
[Feature] Auto generate README.md with Go LC GraphQL package

### PR DESCRIPTION
**Pull request by dataprob**
### 📋 Summary

-   [README.md](https://github.com/Prompt-ing/LeetCode-ing/blob/annieli/README.md) is now auto generated. We've done 101 questions 🎉 (count is finally accurate 👀)
    -   `id`: question number
    -   `title`: can click, links to lc
    -   `difficulty`: 🟢 Easy, 🟡 Medium, 🔴 Hard
    -   `description`: can click, links to question description in md format, pulled by graphql
-   used Go package [leetcodegraphql](https://pkg.go.dev/github.com/WindomZ/leetcode-graphql#section-readme)
-   graphql
    -   [graphql.go](https://github.com/Prompt-ing/LeetCode-ing/blob/annieli/graphql/graphql.go)
    -   [questions.json](https://github.com/Prompt-ing/LeetCode-ing/blob/annieli/data/questions.json)
    -   [questions_id.json](https://github.com/Prompt-ing/LeetCode-ing/blob/annieli/data/questions_id.json) becomes the new list, **need to update this whenever new solus are added**. Not too hard, I break it down to 28 intervals sized 100, 28 * 100 = 2800 questions.
    -   [convert.py](https://github.com/Prompt-ing/LeetCode-ing/blob/annieli/doc/questions/convert.py), convert json to md, similar idea as auto generate `contributors.md`
    -   [questions](https://github.com/Prompt-ing/LeetCode-ing/tree/annieli/doc/questions) folder contains all lc question descriptions for easy access. E.g. [question_1.md](https://github.com/Prompt-ing/LeetCode-ing/blob/annieli/doc/questions/question_1.md) for two-sum

-   moved README contributors and instructions sections to [onboarding](https://github.com/Prompt-ing/LeetCode-ing/tree/annieli/doc/onboarding) folder
-   added more options for formatting tool
-   updated contributors list
-   renamed license, Go, and Java references to new name `LeetCode-ing`

#### Future PR
-   continue building and prettify README
-   better onboarding guides
-   10 missing tests need to be implemented
    -   Py: 28, 209, 560, 739, 974, 1732, 2024, 2090
    -   TS: 14, 2352

### 🧠 Remember to

-   [x] add labels to pr
-   [x] tag reviewers
-   [ ] **after** squash merge, [reset your branch](https://github.com/LeetCube/GitCube/blob/main/pr/vsc.md#:~:text=fix%20commits%20ahead%20of%20main)

<details>
<summary>Draft PR</summary>

-   After initial code review, can convert to **Draft PR** to show your work is in progress
-   This disables merge, and reviewers won't receive notifications
-   After changes, click **Ready for Review**, and reviewers will receive notifications again

</details>
<details>
<summary>Reviewers</summary>

-   🟥 Request Changes: any must-do changes before merging
-   🟨 Comments: any optional changes before merging
-   🟩 Approve: if you are the last reviewer, merge it

</details>

### CODE REVIEW

**Comment by dataprob** [comment]
Still at draft stage, since only 1 example. Draft PR for code sharing.

**Comment by argonaut0** [comment]
I don't see a go.mod file for this module?

**Comment by dataprob** [comment]
> I don't see a go.mod file for this module?

I think the `go.work` file hides the `go.mod` file I have. I'll look up what's `go.work`.

**Comment by dataprob** [comment]
> I don't see a go.mod file for this module?

Turns out I just need to `git add -f`, done!

**Comment by dataprob** [comment]
> I don't see a go.mod file for this module?

Actually, I just learned that we need both `go.work` and `go.mod` in order to run. From go doc
> go work
The go command now supports a "Workspace" mode. If a go.work file is found in the working directory or a parent directory, or one is specified using the GOWORK environment variable, it will put the go command into workspace mode. In workspace mode, the go.work file will be used to determine the set of main modules used as the roots for module resolution, instead of using the normally-found go.mod file to specify the single main module. For more information see the [go work](https://tip.golang.org/pkg/cmd/go#hdr-Workspace_maintenance) documentation.

**Comment by PhaseRush** [comment]
5k line delta and 100+ files, ngl this pr is a bit hard to review. I'll take your word for it and approve for now

**Review by PhaseRush — APPROVED** [review]

**Comment by dataprob** [comment]
> 5k line delta and 100+ files, ngl this pr is a bit hard to review. I'll take your word for it and approve for now

Thanks so much! 🎉🎉 Yeah a good chunk of delta is prob the new question desc files, renaming and formatting 👀

**Pull request merged**
